import React from 'react';

/**
 * A component that renders the Terms of Service for the application.
 * It is a stateless component that contains static legal text.
 * @returns {JSX.Element} The rendered TermsOfService component.
 */
export const TermsOfService: React.FC = () => {
  return (
    <div className="prose prose-invert max-w-none p-6 text-slate-300">
      <h1>Terms of Service for X-Genius</h1>
      <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using X-Genius (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        X-Genius is an application that uses the OpenRouter API to generate content based on user prompts and posts it to X (formerly Twitter) on the user's behalf. The user must provide their own OpenRouter API key and authenticate with their X account.
      </p>

      <h2>3. User Responsibilities</h2>
      <ul>
        <li>
            You are responsible for the security of your OpenRouter API key. This key is stored in your browser and is your responsibility to manage. We are not liable for any loss or damage arising from your failure to comply with this security obligation.
        </li>
        <li>
            You are solely responsible for the content you generate and post using the Service. You agree not to post content that is unlawful, offensive, or violates the rights of others, including X's terms of service.
        </li>
        <li>
            You are responsible for all activities that occur under your account.
        </li>
      </ul>

      <h2>4. Prohibited Conduct</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Violate any applicable laws or regulations.</li>
        <li>Infringe upon the intellectual property rights of others.</li>
        <li>Generate or post content that is hateful, defamatory, or discriminatory.</li>
        <li>Engage in any activity that could harm the Service or its users.</li>
      </ul>

      <h2>5. Disclaimers</h2>
      <p>
        The Service is provided on an "as-is" and "as-available" basis. We make no warranties, express or implied, that the Service will be uninterrupted, error-free, or secure. The accuracy and quality of the content generated by the AI are not guaranteed.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        In no event shall X-Genius or its operators be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, or other intangibles, arising out of or in connection with your use of the Service.
      </p>

      <h2>7. Third-Party Services</h2>
      <p>
        The Service relies on third-party APIs, including OpenRouter and the X API. We are not responsible for the availability or performance of these services. Your use of these third-party services is subject to their respective terms and conditions.
      </p>

      <h2>8. Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms at any time. We will provide notice of any significant changes. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.
      </p>
      
      <h2>9. Contact Us</h2>
      <p>
        If you have any questions about these Terms, please contact us.
      </p>
    </div>
  );
};
